# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f7df4e891f7454f3c20b01ac3d91b4dcb919a1ad808eea14dbc35cbe33ef1a17cc39fe21e456d6de5db76c890d8f77e2d611103a213642307073937fde67e44

test:
  secret_key_base: 6bc790b720def95bd36392624c5475f73c2cbc4d0fcae92b046ba85448767f6c80cd317c2ac8021320e43b84d4940d9ee43f10c0817c29310850f1db1523220c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
